[WIN] Fix DaylightSavingTA This was found in issue 215 - loading ssf.js in Windows will result in an exception in DaylightSavingTA causing it to return a fixed value and display this message:
Warning: Invalid datetime date, assumed DST time, may be inaccurate...

Here is the trace from Python 3.8.5:
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    context.execute(js)
  File "C:\Python38\Js2Py-master\js2py\evaljs.py", line 199, in execute
    exec (compiled, self._context)
  File "<EvalJS snippet>", line 2174, in <module>
  File "C:\Python38\Js2Py-master\js2py\base.py", line 949, in __call__
    return self.call(self.GlobalObject, args)
  File "C:\Python38\Js2Py-master\js2py\base.py", line 1464, in call
    return Js(self.code(*args))
  File "<EvalJS snippet>", line 1541, in PyJs_make_ssf_0_
  File "C:\Python38\Js2Py-master\js2py\constructors\jsdate.py", line 149, in date_constructor
    return date_constructor2(*args)
  File "C:\Python38\Js2Py-master\js2py\constructors\jsdate.py", line 181, in date_constructor2
    LocalToUTC(MakeDate(MakeDay(y, m, dt), MakeTime(h, mi, sec, mili))))
  File "C:\Python38\Js2Py-master\js2py\constructors\time_helpers.py", line 54, in LocalToUTC
    return t - LocalTZA - DaylightSavingTA(t - LocalTZA)
  File "C:\Python38\Js2Py-master\js2py\constructors\time_helpers.py", line 39, in DaylightSavingTA
    LOCAL_ZONE.dst(datetime.datetime.utcfromtimestamp(
OSError: [Errno 22] Invalid argument